### PR TITLE
Bump nginx version to 1.6.2

### PR DESCRIPTION
**Pull request by isaacsu**
Also,
- Update cardboard to 2.1.0.
- Update tests to new `contain_class` rspec syntax.
- Update rvm version to 2.0.0.

/cc @grosser @sandlerr

### CODE REVIEW

**Comment by mfischer-zd** [comment]
What do I have to do with this? :)

**Comment by sandlerr** [comment]
:+1:

**Comment by grosser** [comment]
:+1: please also make a pr to the boxen repo

**Comment by isaacsu** [comment]
@grosser https://github.com/boxen/puppet-nginx/pull/41

**Pull request merged**
